# Generated by Django 4.0.4 on 2022-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movieshow_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
